# Generated by Django 2.2.13 on 2021-06-20 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210620_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='participant_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
