# Generated by Django 2.2.13 on 2021-06-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210620_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='participant',
            new_name='participant_id',
        ),
        migrations.AddField(
            model_name='organizer',
            name='fcm_token',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='fcm_token',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(default=''),
        ),
    ]
