# Generated by Django 2.2.13 on 2021-06-24 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210623_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
