# Generated by Django 2.2.13 on 2021-06-24 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_organizer_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
