# Generated by Django 2.2.13 on 2021-06-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210623_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('O', 'Organizer'), ('P', 'Participant')], max_length=1),
        ),
    ]
