# Generated by Django 2.2.13 on 2021-07-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
